### ISSUE TITLE
Question regarding the status of this binding

### ISSUE THREAD

**Issue by ethan-tqa** [nimious/vulkan#1]
Hi there, I wonder if this binding is usable on Windows x64 now, or some work is required to make it work. Since you said that there are some problems with the compiler, which was a year ago. Another thing is that it was built with SDK 1.0.5.0, which is kinda outdated as well.

**Comment by gmpreussner** [comment]
Hi @ethan-tqa, sorry, I'm currently completely overloaded and have no time to look into this. If you figure it out in the meantime, please send me a pull request, thanks!

**Comment by gmpreussner** [comment]
Hey Ethan, I finally had some time to update the bindings. I installed Nim 0.17.2 x64 on a fresh machine, had it pull Mingw64 via finish.exe, and it compiled, linked and ran successfully. Sorry for the long delay - I've just been too busy at work all year.

**Comment by ethan-tqa** [comment]
Oh wow, cool, I totally forgot about this haha
