### ISSUE TITLE
nimble error

### ISSUE THREAD

**Issue by luntik2012** [nimious/vulkan#6]
```sh
nick /tmp/vulkan $ nimble build
  Verifying dependencies for vulkan@0.2
       Tip: 6 messages have been suppressed, use --verbose to show them.
     Error: Nothing to build. Did you specify a module to build using the `bin` key in your .nimble file?

nick /tmp/vulkan $ !! --verbose
nimble build --verbose
    Setting Nim stdlib prefix to /usr
    Setting Nim stdlib path to /usr/lib/nim
       Info Hint: used config file '/etc/nim.cfg' [Conf]
       Info Hint: used config file '/tmp/vulkan/nim.cfg' [Conf]
       Info usr/lib/nim/system.nim(470, 35) Warning: unknown magic 'Exception' might crash the compiler [UnknownMagic]
       Info usr/lib/nim/system/nimscript.nim(15, 19) Warning: unknown magic 'BuildOS' might crash the compiler [UnknownMagic]
  Verifying dependencies for vulkan@0.2
     Error: Nothing to build. Did you specify a module to build using the `bin` key in your .nimble file?
```
also didn't you think about including your library to https://nim-lang.org/docs/lib.html?

**Comment by Clyybber** [comment]
This is a library not an application, so using nimble build won't do anything.
You need to use `nimble install` or `nimble develop` and then specify `vulkan` as a requirement in your own package. If you want to build the examples in this repo, just use `nim c`

**Comment by luntik2012** [comment]
Oh, thank you. It will be helpful to add it in some README section (e.g. installation)

**Comment by Clyybber** [comment]
@gmpreussner This can be closed, I suppose.

**Comment by gmpreussner** [comment]
Sorry for my delayed response - I'm currently on a sabbatical. Glad you figured it out on your own. Have a great week!

**Comment by luntik2012** [comment]
@Clyybber 

> This can be closed, I suppose.

Yeah, sorry)
